### ISSUE TITLE
Latest version downloads JAR for every run

### ISSUE THREAD

**Issue by Quantas** [mide/minecraft-overviewer#49]
Every time I run this container, I just execute ‘docker start container-name’, it downloads the Minecraft JAR, is there a way to fix? Thanks!!

**Comment by mide** [comment]
Hi @Quantas - this Docker image will download the Minecraft client `.jar` in order to obtain the textures for the render. In order to cache the `.jar`, you'll need to make a mount point so `/home/minecraft/.minecraft/versions/${MINECRAFT_VERSION}/` doesn't go away when the container dies.

https://github.com/mide/minecraft-overviewer/blob/d2fad05fb06a30d6ef40214562e08ad41b8c33b0/entrypoint.sh#L10-L13

I hope this helps; Is the problem you're having around the container not starting a render? Or are you just concerned about caching the Minecraft Client `.jar`?

--- 
The intention is that the `-N` flag passed into `wget` would prevent the downloading the `.jar` when already present. However, after reading [the `wget` `man` page](https://linux.die.net/man/1/wget), I see 
>For this reason, -N (for timestamp-checking) is not supported in combination with -O: since file is always newly created, it will always have a very new timestamp. A warning will be issued if this combination is used.

So there is an open issue ~(#50)~ where I could improve the caching of the Minecraft client `.jar`. I'll take a look as soon as I can. _Edit: I closed #50 as it was just an unnecessary duplicate that I made before I understood these issues were the same._

**Comment by Quantas** [comment]
I am starting the container, and the render works fine. After the first start, I have a cron that runs every 30 minutes on the docker host that just calls `docker run overviewer` which restarts the container. Every time it runs, it downloads the JAR again, probably due to the -N flag on the wget call not working as desired.

**Comment by mide** [comment]
Yeah, I'll sort out the `-N` bug as soon as I get a chance, but you'll still need a volume mapping to ensure the client doesn't get blown away once the container exits. Without the mapping, there wouldn't ever be anything to cache.

**Comment by Quantas** [comment]
I can update my container to have the mapping, thanks for the assistance!

**Comment by mide** [comment]
Solved by #66.
