### ISSUE TITLE
Blue torches are not rendering. 

### ISSUE THREAD

**Issue by daveseff** [mide/minecraft-overviewer#81]
It seems that blue torches are not being rendered. That is all. Thanks.

**Comment by mide** [comment]
Hi there! 

I don't know that this is a problem with this repo, as this is just a Docker wrapper around the [upstream  `overviewer/Minecraft-Overviewer` project](https://github.com/overviewer/Minecraft-Overviewer). I'd open up an issue over there, as they will likely have better debug steps for you.

We do have an open task to switch to using the latest git commit for the source of Overviewer instead of the Debian repository, and it is possible the problem you're seeing could be due to running a slightly older version of the app. This problem could be resolved once we make that switch.

**Comment by daveseff** [comment]
thanks @mide I think I posted this to the wrong repo. I'll close this and open at the official repo. Cheers!
