### ISSUE TITLE
Container not returning/getting stuck at 99% when done

### ISSUE THREAD

**Issue by hannesknutsson** [mide/minecraft-overviewer#84]
My problem is that when the render reach 99% the output stops, but the container/process/script does not die.

The python3 processes lay dormant and do seemingly nothing (between 1 and 10% cpu utilisation) in all eternity.

I tried killing the process when it's done (when it gets stuck at 99%), but when I do that, the script leaves some type of trace that it did not end in a clean way. The next run will then pick up on this and invalidates the previous run because it "broke". Then it will start rendering the WHOLE world all over again even though only a very few couple of chunks changed since the last render.

All I want is for the script/container to exit nicely when it is done so that I can run it every now and then without having to render unchanged parts of the world again.

Otherwise a great image! Thanks for providing it :)

**Comment by mide** [comment]
Hi there! 

I don't know that this is a problem with this repo, as this is just a Docker wrapper around the [upstream  `overviewer/Minecraft-Overviewer` project](https://github.com/overviewer/Minecraft-Overviewer). I'd open up an issue over there, as they will likely have better debug steps for you.

We do have an open task to switch to using the latest git commit for the source of Overviewer instead of the Debian repository, and it is possible the problem you're seeing could be due to running a slightly older version of the app. This problem could be resolved once we make that switch.

**Comment by hannesknutsson** [comment]
Yeah, you're right.

I tried running from source and the problem seems to have been resolved.

Sorry for bothering you :)
